### PR TITLE
Migrate schema from 2.2.0 to 2.4.0

### PR DESCRIPTION
**Pull request by ThibaultMarzullo**
Update XMLs to BSync schema v2.4.0, [To-do #93](https://github.com/BuildingSync/project-tracker/issues/93).

### CODE REVIEW

**Comment by ThibaultMarzullo** [comment]
@nllong , the model articulation tests fail because the year in the IDF files do not match, see below. Is there something I can do to fix that?
```
IDF file 2 successfully saved
This is the newly create idf file line :   2021,                                   !- Begin Year
 on line no : 2477
This is the original idf file line :   2022,                                   !- Begin Year
 on line no : 2477
This is the newly create idf file line :   2021,                                   !- End Year
 on line no : 2480
This is the original idf file line :   2022,                                   !- End Year
 on line no : 2480
This is the newly create idf file line :   Friday,                                 !- Day of Week for Start Day
 on line no : 2481
This is the original idf file line :   Saturday,                               !- Day of Week for Start Day
 on line no : 2481
  Should write the same IDF file as previously generated (FAILED - 1)
  ```

**Comment by nllong** [comment]
you should be able to just change the year in the comparison file to 2022... https://github.com/BuildingSync/BuildingSync-gem/blob/develop/spec/files/filecomparison/originalfiles/in.idf#L2478-L2481, and the day of week to Friday.

**Comment by nllong** [comment]
sweet, all passing now, merging!!!

**Review by nllong — COMMENTED** [review]
🚀

**Pull request merged**
