### PR TITLE
default to bsync version 2.2.0

### PR DESCRIPTION
**Pull request by nllong**

### CODE REVIEW

**Review by macintoshpie — APPROVED** [review]
Looks good, but why not 2.3.0?

**Comment by nllong** [comment]
2.3.0 is not supported in this gem yet. When we do the upgrade we can also update this version. If cool, then can you merge?

**Comment by macintoshpie** [comment]
Ah gotcha. I don't have write access to the repo so I can't merge

**Comment by nllong** [comment]
doh, I'll grant you whatever you need. Merging for now.

**Pull request merged**
